//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ChinaBankControlLibrary.RemittancePartnerWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RemittancePartnerWebServiceSoap", Namespace="http://pjlhuillier.org/remittance/partner/nybp")]
    public partial class RemittancePartnerWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ExposeProxyClassesOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemittancePartnerLookupOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemittancePartnerPayoutOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RemittancePartnerWebService() {
            this.Url = global::ChinaBankControlLibrary.Properties.Settings.Default.ChinaBankControlLibrary_RemittancePartnerWebReference_RemittancePartnerWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ExposeProxyClassesCompletedEventHandler ExposeProxyClassesCompleted;
        
        /// <remarks/>
        public event RemittancePartnerLookupCompletedEventHandler RemittancePartnerLookupCompleted;
        
        /// <remarks/>
        public event RemittancePartnerPayoutCompletedEventHandler RemittancePartnerPayoutCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pjlhuillier.org/remittance/partner/nybp/ExposeProxyClasses", RequestNamespace="http://pjlhuillier.org/remittance/partner/nybp", ResponseNamespace="http://pjlhuillier.org/remittance/partner/nybp", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExposeProxyClasses(CebuanaCustomerInformation cebuanaCustomerInformation, CebuanaCustomerID cebuanaCustomerID) {
            this.Invoke("ExposeProxyClasses", new object[] {
                        cebuanaCustomerInformation,
                        cebuanaCustomerID});
        }
        
        /// <remarks/>
        public void ExposeProxyClassesAsync(CebuanaCustomerInformation cebuanaCustomerInformation, CebuanaCustomerID cebuanaCustomerID) {
            this.ExposeProxyClassesAsync(cebuanaCustomerInformation, cebuanaCustomerID, null);
        }
        
        /// <remarks/>
        public void ExposeProxyClassesAsync(CebuanaCustomerInformation cebuanaCustomerInformation, CebuanaCustomerID cebuanaCustomerID, object userState) {
            if ((this.ExposeProxyClassesOperationCompleted == null)) {
                this.ExposeProxyClassesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExposeProxyClassesOperationCompleted);
            }
            this.InvokeAsync("ExposeProxyClasses", new object[] {
                        cebuanaCustomerInformation,
                        cebuanaCustomerID}, this.ExposeProxyClassesOperationCompleted, userState);
        }
        
        private void OnExposeProxyClassesOperationCompleted(object arg) {
            if ((this.ExposeProxyClassesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExposeProxyClassesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pjlhuillier.org/remittance/partner/nybp/RemittancePartnerLookup", RequestNamespace="http://pjlhuillier.org/remittance/partner/nybp", ResponseNamespace="http://pjlhuillier.org/remittance/partner/nybp", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LookupTransactionResult RemittancePartnerLookup(LookupTransactionRequest lookupTransactionRequest) {
            object[] results = this.Invoke("RemittancePartnerLookup", new object[] {
                        lookupTransactionRequest});
            return ((LookupTransactionResult)(results[0]));
        }
        
        /// <remarks/>
        public void RemittancePartnerLookupAsync(LookupTransactionRequest lookupTransactionRequest) {
            this.RemittancePartnerLookupAsync(lookupTransactionRequest, null);
        }
        
        /// <remarks/>
        public void RemittancePartnerLookupAsync(LookupTransactionRequest lookupTransactionRequest, object userState) {
            if ((this.RemittancePartnerLookupOperationCompleted == null)) {
                this.RemittancePartnerLookupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemittancePartnerLookupOperationCompleted);
            }
            this.InvokeAsync("RemittancePartnerLookup", new object[] {
                        lookupTransactionRequest}, this.RemittancePartnerLookupOperationCompleted, userState);
        }
        
        private void OnRemittancePartnerLookupOperationCompleted(object arg) {
            if ((this.RemittancePartnerLookupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemittancePartnerLookupCompleted(this, new RemittancePartnerLookupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pjlhuillier.org/remittance/partner/nybp/RemittancePartnerPayout", RequestNamespace="http://pjlhuillier.org/remittance/partner/nybp", ResponseNamespace="http://pjlhuillier.org/remittance/partner/nybp", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PayoutTransactionResult RemittancePartnerPayout(PayoutTransactionRequest payoutTransactionRequest) {
            object[] results = this.Invoke("RemittancePartnerPayout", new object[] {
                        payoutTransactionRequest});
            return ((PayoutTransactionResult)(results[0]));
        }
        
        /// <remarks/>
        public void RemittancePartnerPayoutAsync(PayoutTransactionRequest payoutTransactionRequest) {
            this.RemittancePartnerPayoutAsync(payoutTransactionRequest, null);
        }
        
        /// <remarks/>
        public void RemittancePartnerPayoutAsync(PayoutTransactionRequest payoutTransactionRequest, object userState) {
            if ((this.RemittancePartnerPayoutOperationCompleted == null)) {
                this.RemittancePartnerPayoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemittancePartnerPayoutOperationCompleted);
            }
            this.InvokeAsync("RemittancePartnerPayout", new object[] {
                        payoutTransactionRequest}, this.RemittancePartnerPayoutOperationCompleted, userState);
        }
        
        private void OnRemittancePartnerPayoutOperationCompleted(object arg) {
            if ((this.RemittancePartnerPayoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemittancePartnerPayoutCompleted(this, new RemittancePartnerPayoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pjlhuillier.org/remittance/partner/nybp")]
    public partial class CebuanaCustomerInformation {
        
        private string customerNumberField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string cityField;
        
        private string countryField;
        
        private CebuanaCustomerID[] registeredIDsField;
        
        private CebuanaCustomerID[] secondaryIDsField;
        
        private string pickupDateField;
        
        private string reasonRemarksField;
        
        private string primaryIDIssuanceDateField;
        
        private string primaryIDExpirationdateField;
        
        private string secondaryIDCodeField;
        
        private string secondaryIDTypeField;
        
        private string secondaryIDNumberField;
        
        private string secondaryIDIssuanceDateField;
        
        private string secondaryIDExpirationdateField;
        
        private string receiverStreetField;
        
        private string receiverBarangayField;
        
        private string receiverProvinceField;
        
        private string receiverZipCodeField;
        
        private int mobileNumberField;
        
        private string emailAddressField;
        
        private string dateOfBirthField;
        
        /// <remarks/>
        public string CustomerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                this.customerNumberField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public CebuanaCustomerID[] RegisteredIDs {
            get {
                return this.registeredIDsField;
            }
            set {
                this.registeredIDsField = value;
            }
        }
        
        /// <remarks/>
        public CebuanaCustomerID[] SecondaryIDs {
            get {
                return this.secondaryIDsField;
            }
            set {
                this.secondaryIDsField = value;
            }
        }
        
        /// <remarks/>
        public string PickupDate {
            get {
                return this.pickupDateField;
            }
            set {
                this.pickupDateField = value;
            }
        }
        
        /// <remarks/>
        public string ReasonRemarks {
            get {
                return this.reasonRemarksField;
            }
            set {
                this.reasonRemarksField = value;
            }
        }
        
        /// <remarks/>
        public string PrimaryIDIssuanceDate {
            get {
                return this.primaryIDIssuanceDateField;
            }
            set {
                this.primaryIDIssuanceDateField = value;
            }
        }
        
        /// <remarks/>
        public string PrimaryIDExpirationdate {
            get {
                return this.primaryIDExpirationdateField;
            }
            set {
                this.primaryIDExpirationdateField = value;
            }
        }
        
        /// <remarks/>
        public string SecondaryIDCode {
            get {
                return this.secondaryIDCodeField;
            }
            set {
                this.secondaryIDCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SecondaryIDType {
            get {
                return this.secondaryIDTypeField;
            }
            set {
                this.secondaryIDTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SecondaryIDNumber {
            get {
                return this.secondaryIDNumberField;
            }
            set {
                this.secondaryIDNumberField = value;
            }
        }
        
        /// <remarks/>
        public string SecondaryIDIssuanceDate {
            get {
                return this.secondaryIDIssuanceDateField;
            }
            set {
                this.secondaryIDIssuanceDateField = value;
            }
        }
        
        /// <remarks/>
        public string SecondaryIDExpirationdate {
            get {
                return this.secondaryIDExpirationdateField;
            }
            set {
                this.secondaryIDExpirationdateField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverStreet {
            get {
                return this.receiverStreetField;
            }
            set {
                this.receiverStreetField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverBarangay {
            get {
                return this.receiverBarangayField;
            }
            set {
                this.receiverBarangayField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverProvince {
            get {
                return this.receiverProvinceField;
            }
            set {
                this.receiverProvinceField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverZipCode {
            get {
                return this.receiverZipCodeField;
            }
            set {
                this.receiverZipCodeField = value;
            }
        }
        
        /// <remarks/>
        public int MobileNumber {
            get {
                return this.mobileNumberField;
            }
            set {
                this.mobileNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pjlhuillier.org/remittance/partner/nybp")]
    public partial class CebuanaCustomerID {
        
        private string iDCodeField;
        
        private string iDDescriptionField;
        
        /// <remarks/>
        public string IDCode {
            get {
                return this.iDCodeField;
            }
            set {
                this.iDCodeField = value;
            }
        }
        
        /// <remarks/>
        public string IDDescription {
            get {
                return this.iDDescriptionField;
            }
            set {
                this.iDDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pjlhuillier.org/remittance/partner/nybp")]
    public partial class PayoutTransactionResult {
        
        private PayoutTransactionResultCode resultCodeField;
        
        private string messageToClientField;
        
        private string transactionNumberField;
        
        private System.DateTime payoutDateField;
        
        /// <remarks/>
        public PayoutTransactionResultCode ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MessageToClient {
            get {
                return this.messageToClientField;
            }
            set {
                this.messageToClientField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionNumber {
            get {
                return this.transactionNumberField;
            }
            set {
                this.transactionNumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PayoutDate {
            get {
                return this.payoutDateField;
            }
            set {
                this.payoutDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pjlhuillier.org/remittance/partner/nybp")]
    public enum PayoutTransactionResultCode {
        
        /// <remarks/>
        UnrecognizedResponse,
        
        /// <remarks/>
        Successful,
        
        /// <remarks/>
        Unsuccessful,
        
        /// <remarks/>
        PartnerError,
        
        /// <remarks/>
        ServerError,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pjlhuillier.org/remittance/partner/nybp")]
    public partial class PayoutTransactionRequest {
        
        private CebuanaBranchInformation cebuanaBranchInformationField;
        
        private string transactionNumberField;
        
        private decimal payoutAmountField;
        
        private string sendingCurrencyField;
        
        private string payoutCurrencyField;
        
        private decimal currencyConversionRateField;
        
        private string payoutCountryField;
        
        private string senderLastNameField;
        
        private string senderFirstNameField;
        
        private string receiverCustomerNumberField;
        
        private string receiverLastNameField;
        
        private string receiverFirstNameField;
        
        private string receiverIDCodeField;
        
        private string receiverIDTypeField;
        
        private string receiverIDNumberField;
        
        private string receiverCityField;
        
        private string receiverCountryField;
        
        private string sessionIDField;
        
        private string pickupDateField;
        
        private string reasonRemarksField;
        
        private string primaryIDIssuanceDateField;
        
        private string primaryIDExpirationdateField;
        
        private string secondaryIDCodeField;
        
        private string secondaryIDTypeField;
        
        private string secondaryIDNumberField;
        
        private string secondaryIDIssuanceDateField;
        
        private string secondaryIDExpirationdateField;
        
        private string receiverStreetField;
        
        private string receiverBarangayField;
        
        private string receiverProvinceField;
        
        private string receiverZipCodeField;
        
        private int mobileNumberField;
        
        private string emailAddressField;
        
        private string dateOfBirthField;
        
        /// <remarks/>
        public CebuanaBranchInformation CebuanaBranchInformation {
            get {
                return this.cebuanaBranchInformationField;
            }
            set {
                this.cebuanaBranchInformationField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionNumber {
            get {
                return this.transactionNumberField;
            }
            set {
                this.transactionNumberField = value;
            }
        }
        
        /// <remarks/>
        public decimal PayoutAmount {
            get {
                return this.payoutAmountField;
            }
            set {
                this.payoutAmountField = value;
            }
        }
        
        /// <remarks/>
        public string SendingCurrency {
            get {
                return this.sendingCurrencyField;
            }
            set {
                this.sendingCurrencyField = value;
            }
        }
        
        /// <remarks/>
        public string PayoutCurrency {
            get {
                return this.payoutCurrencyField;
            }
            set {
                this.payoutCurrencyField = value;
            }
        }
        
        /// <remarks/>
        public decimal CurrencyConversionRate {
            get {
                return this.currencyConversionRateField;
            }
            set {
                this.currencyConversionRateField = value;
            }
        }
        
        /// <remarks/>
        public string PayoutCountry {
            get {
                return this.payoutCountryField;
            }
            set {
                this.payoutCountryField = value;
            }
        }
        
        /// <remarks/>
        public string SenderLastName {
            get {
                return this.senderLastNameField;
            }
            set {
                this.senderLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string SenderFirstName {
            get {
                return this.senderFirstNameField;
            }
            set {
                this.senderFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverCustomerNumber {
            get {
                return this.receiverCustomerNumberField;
            }
            set {
                this.receiverCustomerNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverLastName {
            get {
                return this.receiverLastNameField;
            }
            set {
                this.receiverLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverFirstName {
            get {
                return this.receiverFirstNameField;
            }
            set {
                this.receiverFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverIDCode {
            get {
                return this.receiverIDCodeField;
            }
            set {
                this.receiverIDCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverIDType {
            get {
                return this.receiverIDTypeField;
            }
            set {
                this.receiverIDTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverIDNumber {
            get {
                return this.receiverIDNumberField;
            }
            set {
                this.receiverIDNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverCity {
            get {
                return this.receiverCityField;
            }
            set {
                this.receiverCityField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverCountry {
            get {
                return this.receiverCountryField;
            }
            set {
                this.receiverCountryField = value;
            }
        }
        
        /// <remarks/>
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        public string PickupDate {
            get {
                return this.pickupDateField;
            }
            set {
                this.pickupDateField = value;
            }
        }
        
        /// <remarks/>
        public string ReasonRemarks {
            get {
                return this.reasonRemarksField;
            }
            set {
                this.reasonRemarksField = value;
            }
        }
        
        /// <remarks/>
        public string PrimaryIDIssuanceDate {
            get {
                return this.primaryIDIssuanceDateField;
            }
            set {
                this.primaryIDIssuanceDateField = value;
            }
        }
        
        /// <remarks/>
        public string PrimaryIDExpirationdate {
            get {
                return this.primaryIDExpirationdateField;
            }
            set {
                this.primaryIDExpirationdateField = value;
            }
        }
        
        /// <remarks/>
        public string SecondaryIDCode {
            get {
                return this.secondaryIDCodeField;
            }
            set {
                this.secondaryIDCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SecondaryIDType {
            get {
                return this.secondaryIDTypeField;
            }
            set {
                this.secondaryIDTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SecondaryIDNumber {
            get {
                return this.secondaryIDNumberField;
            }
            set {
                this.secondaryIDNumberField = value;
            }
        }
        
        /// <remarks/>
        public string SecondaryIDIssuanceDate {
            get {
                return this.secondaryIDIssuanceDateField;
            }
            set {
                this.secondaryIDIssuanceDateField = value;
            }
        }
        
        /// <remarks/>
        public string SecondaryIDExpirationdate {
            get {
                return this.secondaryIDExpirationdateField;
            }
            set {
                this.secondaryIDExpirationdateField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverStreet {
            get {
                return this.receiverStreetField;
            }
            set {
                this.receiverStreetField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverBarangay {
            get {
                return this.receiverBarangayField;
            }
            set {
                this.receiverBarangayField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverProvince {
            get {
                return this.receiverProvinceField;
            }
            set {
                this.receiverProvinceField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverZipCode {
            get {
                return this.receiverZipCodeField;
            }
            set {
                this.receiverZipCodeField = value;
            }
        }
        
        /// <remarks/>
        public int MobileNumber {
            get {
                return this.mobileNumberField;
            }
            set {
                this.mobileNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pjlhuillier.org/remittance/partner/nybp")]
    public partial class CebuanaBranchInformation {
        
        private string branchUserIDField;
        
        private string branchNameField;
        
        private string branchCodeField;
        
        private string branchAreaCodeField;
        
        private string branchRegionCodeField;
        
        private string clientApplicationVersionField;
        
        private string clientMacAddressField;
        
        /// <remarks/>
        public string BranchUserID {
            get {
                return this.branchUserIDField;
            }
            set {
                this.branchUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string BranchName {
            get {
                return this.branchNameField;
            }
            set {
                this.branchNameField = value;
            }
        }
        
        /// <remarks/>
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BranchAreaCode {
            get {
                return this.branchAreaCodeField;
            }
            set {
                this.branchAreaCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BranchRegionCode {
            get {
                return this.branchRegionCodeField;
            }
            set {
                this.branchRegionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ClientApplicationVersion {
            get {
                return this.clientApplicationVersionField;
            }
            set {
                this.clientApplicationVersionField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMacAddress {
            get {
                return this.clientMacAddressField;
            }
            set {
                this.clientMacAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pjlhuillier.org/remittance/partner/nybp")]
    public partial class LookupTransactionResult {
        
        private LookupTransactionResultCode resultCodeField;
        
        private string messageToClientField;
        
        private string transactionNumberField;
        
        private TransactionStatus transactionStatusField;
        
        private System.DateTime transactionDateField;
        
        private decimal payoutAmountField;
        
        private string payoutCurrencyField;
        
        private string payoutCountryField;
        
        private string senderLastNameField;
        
        private string senderFirstNameField;
        
        private string beneficiaryLastNameField;
        
        private string beneficiaryFirstNameField;
        
        private string multiCurrencyPayoutCodeField;
        
        private string sessionIDField;
        
        /// <remarks/>
        public LookupTransactionResultCode ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MessageToClient {
            get {
                return this.messageToClientField;
            }
            set {
                this.messageToClientField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionNumber {
            get {
                return this.transactionNumberField;
            }
            set {
                this.transactionNumberField = value;
            }
        }
        
        /// <remarks/>
        public TransactionStatus TransactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
            }
        }
        
        /// <remarks/>
        public decimal PayoutAmount {
            get {
                return this.payoutAmountField;
            }
            set {
                this.payoutAmountField = value;
            }
        }
        
        /// <remarks/>
        public string PayoutCurrency {
            get {
                return this.payoutCurrencyField;
            }
            set {
                this.payoutCurrencyField = value;
            }
        }
        
        /// <remarks/>
        public string PayoutCountry {
            get {
                return this.payoutCountryField;
            }
            set {
                this.payoutCountryField = value;
            }
        }
        
        /// <remarks/>
        public string SenderLastName {
            get {
                return this.senderLastNameField;
            }
            set {
                this.senderLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string SenderFirstName {
            get {
                return this.senderFirstNameField;
            }
            set {
                this.senderFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string BeneficiaryLastName {
            get {
                return this.beneficiaryLastNameField;
            }
            set {
                this.beneficiaryLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string BeneficiaryFirstName {
            get {
                return this.beneficiaryFirstNameField;
            }
            set {
                this.beneficiaryFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string MultiCurrencyPayoutCode {
            get {
                return this.multiCurrencyPayoutCodeField;
            }
            set {
                this.multiCurrencyPayoutCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pjlhuillier.org/remittance/partner/nybp")]
    public enum LookupTransactionResultCode {
        
        /// <remarks/>
        UnrecognizedResponse,
        
        /// <remarks/>
        Successful,
        
        /// <remarks/>
        Unsuccessful,
        
        /// <remarks/>
        PartnerError,
        
        /// <remarks/>
        ServerError,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pjlhuillier.org/remittance/partner/nybp")]
    public enum TransactionStatus {
        
        /// <remarks/>
        UnrecognizedStatus,
        
        /// <remarks/>
        ForPayout,
        
        /// <remarks/>
        Blocked,
        
        /// <remarks/>
        PaidOut,
        
        /// <remarks/>
        Cancelled,
        
        /// <remarks/>
        ProcessedForPayout,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pjlhuillier.org/remittance/partner/nybp")]
    public partial class LookupTransactionRequest {
        
        private string transactionNumberField;
        
        private CebuanaBranchInformation cebuanaBranchInformationField;
        
        /// <remarks/>
        public string TransactionNumber {
            get {
                return this.transactionNumberField;
            }
            set {
                this.transactionNumberField = value;
            }
        }
        
        /// <remarks/>
        public CebuanaBranchInformation CebuanaBranchInformation {
            get {
                return this.cebuanaBranchInformationField;
            }
            set {
                this.cebuanaBranchInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ExposeProxyClassesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RemittancePartnerLookupCompletedEventHandler(object sender, RemittancePartnerLookupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemittancePartnerLookupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemittancePartnerLookupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LookupTransactionResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LookupTransactionResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RemittancePartnerPayoutCompletedEventHandler(object sender, RemittancePartnerPayoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemittancePartnerPayoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemittancePartnerPayoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PayoutTransactionResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PayoutTransactionResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591